-define(DIN_REF, '_._din').
-define(NUM_FORKS, 5).
-define(CUR_SEAT, 0).
-define(THINK_FACTOR, 1000).
-define(EATING_TIME, 1000).
-define(DEFAULT_FILE_NAME, "dining_log.txt").
-define(DEFAULT_RUNNING_TIME, 100000).
